# Generated by Django 6.0.2 on 2026-07-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0015_alter_salesinvoice_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'SaaS Platform Admin'), ('Owner', 'Tenant Shop Owner'), ('Manager', 'Store Manager'), ('Salesman', 'Salesman / Billing Clerk'), ('Inventory', 'Inventory & Purchase Clerk'), ('Delivery Boy', 'Delivery Boy / Field Operator')], default='Salesman', max_length=50),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('model_name', models.CharField(max_length=100, verbose_name='Module / Model')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Object Name / Info')),
                ('description', models.TextField(verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Logged At')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=100, verbose_name='Return Number')),
                ('return_date', models.DateField(verbose_name='Return Date')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Amount (₹)')),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='GST Amount (₹)')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Refund (₹)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='wholesaleApp.suppliermaster', verbose_name='Supplier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Rate (₹)')),
                ('quantity', models.IntegerField(verbose_name='Returned Qty')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (₹)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaleApp.productmaster', verbose_name='Product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesaleApp.purchasereturn')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=100, verbose_name='Return Number')),
                ('return_date', models.DateField(verbose_name='Return Date')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Amount (₹)')),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='GST Amount (₹)')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Refund (₹)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='wholesaleApp.customermaster', verbose_name='Customer')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'verbose_name_plural': 'Sales Returns',
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Rate (₹)')),
                ('quantity', models.IntegerField(verbose_name='Returned Qty')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (₹)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaleApp.productbatch', verbose_name='Batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaleApp.productmaster', verbose_name='Product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesaleApp.salesreturn')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Scheme Name')),
                ('billed_qty', models.IntegerField(default=0, verbose_name='Billed Qty')),
                ('free_qty', models.IntegerField(default=0, verbose_name='Free Qty')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount (%)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='wholesaleApp.productmaster', verbose_name='Product')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Scheme Master',
                'verbose_name_plural': 'Scheme Masters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Paid (₹)')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque')], default='Cash', max_length=20, verbose_name='Payment Mode')),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref / Trans No.')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wholesaleApp.suppliermaster', verbose_name='Supplier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
