# Generated by Django 6.0.2 on 2026-07-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0016_alter_userprofile_role_activitylog_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='wholesaleApp.salesinvoice', verbose_name='Adjusted Invoice'),
        ),
    ]
