# Generated by Django 6.0.2 on 2026-07-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0017_customerpayment_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Host')),
                ('email_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('email_host_user', models.EmailField(max_length=255, verbose_name='SMTP Username / Email')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='SMTP Password')),
                ('default_from_email', models.CharField(blank=True, help_text="e.g. 'Your Company <sales@yourcompany.com>'", max_length=255, null=True, verbose_name='Default Sender Display Name/Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='wholesaleApp.tenant', verbose_name='Tenant / Firm')),
            ],
            options={
                'verbose_name': 'Tenant Email Config',
                'verbose_name_plural': 'Tenant Email Configs',
            },
        ),
    ]
