# Generated by Django 6.0.2 on 2026-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0019_salesinvoice_assigned_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'SaaS Platform Admin'), ('Owner', 'Tenant Shop Owner'), ('Manager', 'Store Manager'), ('Salesman', 'Salesman / Billing Clerk'), ('MR', 'Medical Representative (MR)'), ('Inventory', 'Inventory & Purchase Clerk'), ('Delivery Boy', 'Delivery Boy / Field Operator')], default='Salesman', max_length=50),
        ),
    ]
