# Generated by Django 6.0.2 on 2026-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0020_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='units_per_strip',
            field=models.IntegerField(default=1, verbose_name='Conversion Factor (Units per Strip)'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_retail',
            field=models.BooleanField(default=False, verbose_name='Is Retail Bill (B2C)'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='is_retail',
            field=models.BooleanField(default=False, verbose_name='Is Retail Line'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_mode',
            field=models.CharField(choices=[('Wholesale', 'Wholesale Only'), ('Dual', 'Retail + Wholesale (Dual Mode)')], default='Wholesale', max_length=20, verbose_name='Business Mode'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Available Stock (Packs)'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Free Qty'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Billed Qty'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Returned Qty'),
        ),
    ]
