# Generated by Django 6.0.2 on 2026-07-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0021_productmaster_units_per_strip_salesinvoice_is_retail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Doctor Name'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='patient_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Patient Mobile'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='wholesaleApp.customermaster', verbose_name='Customer'),
        ),
    ]
