# Generated by Django 6.0.2 on 2026-07-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0022_salesinvoice_doctor_name_salesinvoice_patient_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gst_dealer_type',
            field=models.CharField(choices=[('Regular', 'Registered (Regular)'), ('Composition', 'Registered (Composition Scheme)'), ('Unregistered', 'Unregistered')], default='Regular', max_length=20, verbose_name='GST Dealer Type'),
        ),
    ]
