# Generated by Django 6.0.2 on 2026-08-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0024_financialyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tally_export_enabled',
            field=models.BooleanField(default=False, verbose_name='Tally Export Integration Enabled'),
        ),
    ]
