# Generated by Django 6.0.2 on 2026-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0026_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='dl_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Drug License Expiry Date'),
        ),
    ]
