# Generated by Django 6.0.2 on 2026-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0027_tenant_dl_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaster',
            name='is_out_state',
            field=models.BooleanField(default=False, verbose_name='Out of State / Interstate (IGST)'),
        ),
    ]
