# Generated by Django 6.0.2 on 2026-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0028_suppliermaster_is_out_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='cn_adjusted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Credit Note Adjusted (₹)'),
        ),
    ]
