# Generated by Django 6.0.2 on 2026-09-19 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0029_salesinvoice_cn_adjusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='adjusted_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_credit_notes', to='wholesaleApp.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='is_adjusted',
            field=models.BooleanField(default=False, verbose_name='Is Credit Note Adjusted'),
        ),
    ]
