# Generated by Django 6.0.6 on 2026-09-20 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0030_salesreturn_adjusted_invoice_salesreturn_is_adjusted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerManageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_discount_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Item Discount % (Rate A)')),
                ('item_discount_b', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Item Discount % (Rate B)')),
                ('item_discount_c', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Item Discount % (Rate C)')),
                ('collection_disc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Collection Disc. %')),
                ('min_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Min. Margin %')),
                ('volume_disc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Volume Disc. %')),
                ('breakage_expiry_disc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Breakage/Expiry Disc. % [MRP]')),
                ('product_scheme_notes', models.TextField(blank=True, null=True, verbose_name='Product Scheme & Special Deals Notes')),
                ('sales_rate_type', models.CharField(choices=[('wholesale', 'Wholesale Rate'), ('mrp', 'MRP'), ('purchase', 'Purchase Rate'), ('rate_a', 'Rate A'), ('rate_b', 'Rate B')], default='wholesale', max_length=30, verbose_name='Sales Rate')),
                ('near_expiry_action', models.CharField(choices=[('allowed', 'Allowed'), ('warn', 'Warn Only'), ('not_allowed', 'Not Allowed')], default='allowed', max_length=20, verbose_name='Near Expiry in Bill')),
                ('new_item_billing', models.BooleanField(default=True, verbose_name='New Item Billing Allowed')),
                ('print_batch', models.BooleanField(default=True, verbose_name='Print Batch on Bill')),
                ('invoice_format', models.CharField(blank=True, default='DEFAULT', max_length=50, null=True, verbose_name='Invoice Format')),
                ('credit_limit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Credit Limit (₹)')),
                ('credit_limit_bills', models.IntegerField(default=0, verbose_name='Credit Limit (Bills)')),
                ('credit_days', models.IntegerField(default=0, verbose_name='Credit Days')),
                ('interest_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Overdue Interest %')),
                ('credit_limit_action', models.CharField(choices=[('indicate', 'Only Indicate / Warn'), ('stop', 'Stop / Block Billing'), ('none', 'No Restriction')], default='indicate', max_length=20, verbose_name='Credit Limit Action')),
                ('bank_rebate_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Bank Rebate %')),
                ('bank_rebate_days', models.IntegerField(default=0, verbose_name='Bank Rebate Upto (Days)')),
                ('collection_days', models.CharField(blank=True, default='Mon,Tue,Wed,Thu,Fri,Sat', max_length=100, null=True, verbose_name='Collection Days')),
                ('transport_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Transport')),
                ('delivery_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Delivery By / Agent')),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bank Name')),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account No')),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code')),
                ('bank_branch', models.CharField(blank=True, max_length=150, null=True, verbose_name='Branch Name')),
                ('operator_note', models.TextField(blank=True, null=True, verbose_name='Operator Note / Billing Alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manage_detail', to='wholesaleApp.customermaster', verbose_name='Customer')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Customer Manage Detail',
                'verbose_name_plural': 'Customer Manage Details',
            },
        ),
    ]
