# Generated by Django 6.0.6 on 2026-09-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0031_customermanagedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='rate_c',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rate C / Special Rate (₹)'),
        ),
        migrations.AddField(
            model_name='purchaseentryitem',
            name='rate_c',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rate C / Special Rate (₹)'),
        ),
    ]
