# Generated by Django 6.0.6 on 2026-09-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0032_productbatch_rate_c_purchaseentryitem_rate_c'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseentry',
            unique_together={('tenant', 'invoice_number')},
        ),
    ]
