# Generated by Django 6.0.2 on 2026-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0033_alter_purchaseentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=10, verbose_name='Payment Type'),
        ),
    ]
