# Generated by Django 6.0.6 on 2026-09-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0034_alter_salesinvoice_payment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Invoice Number'),
        ),
    ]
