# Generated by Django 6.0.2 on 2026-09-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0035_alter_salesinvoice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='dl_number_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='dl_number_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='dl_number_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suppliermaster',
            name='dl_number_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suppliermaster',
            name='dl_number_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suppliermaster',
            name='dl_number_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
