# Generated by Django 6.0.2 on 2026-09-23 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0036_alter_customermaster_dl_number_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category / Expense Head')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (₹)')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI/Online', 'UPI / Online'), ('Bank Transfer', 'Bank Transfer / NEFT'), ('Cheque', 'Cheque')], default='Cash', max_length=20, verbose_name='Payment Mode')),
                ('paid_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paid To / Payee')),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Receipt / Voucher / Ref No')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Description / Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='wholesaleApp.expensecategory', verbose_name='Expense Category')),
            ],
            options={
                'verbose_name': 'Expense Voucher',
                'verbose_name_plural': 'Expense Vouchers',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
