# Generated by Django 6.0.2 on 2026-09-23 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0037_expensecategory_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Schedule Name (e.g. Schedule H, Schedule H1)')),
                ('code', models.CharField(max_length=20, verbose_name='Schedule Code (e.g. H, H1, X, OTC)')),
                ('warning_text', models.TextField(blank=True, null=True, verbose_name='Statutory Warning / Prescription Note')),
                ('requires_prescription', models.BooleanField(default=True, verbose_name='Prescription Required (Rx)')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Schedule Master',
                'verbose_name_plural': 'Schedule Masters',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productmaster',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='wholesaleApp.schedulemaster', verbose_name='Drug Schedule'),
        ),
        migrations.CreateModel(
            name='TaxMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tax Slab Name (e.g. 12% Standard Pharma)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total GST Rate (%)')),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='CGST Rate (%)')),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='SGST Rate (%)')),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IGST Rate (%)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Slab for Products')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Remarks')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Tax Master',
                'verbose_name_plural': 'Tax Masters',
                'ordering': ['rate', 'name'],
                'unique_together': {('tenant', 'rate', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productmaster',
            name='tax_slab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='wholesaleApp.taxmaster', verbose_name='Tax Slab (GST)'),
        ),
    ]
