# Generated by Django 6.0.2 on 2026-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0038_schedulemaster_productmaster_schedule_taxmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='eway_bill',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E-Way Bill Number'),
        ),
    ]
