# Generated by Django 6.0.2 on 2026-09-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0040_medicalrepresentative_salesinvoice_mr'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrepresentative',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission (%)'),
        ),
        migrations.AddField(
            model_name='medicalrepresentative',
            name='monthly_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly Sales Target (₹)'),
        ),
    ]
